[package]
name = "async_with_callback"
version = "0.1.0"
authors = ["user1"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minimio = { path = "../minimio_copy" }